services:

  nginx:
    image: "kum_nginx:v1.31.3"
    build:
      context: ./_nginx
    stop_signal: SIGTERM
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8118:8118"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./_nginx/ssl_params.conf:/etc/nginx/ssl_params.conf:ro
      - ./_nginx/acl:/etc/nginx/watch
      - ./_mirror/certs:/etc/nginx/ssl:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          memory: 32M
    networks:
      mirror_net:
        ipv4_address: 172.200.0.20
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mirror:
    image: "kum_mirror:v3.1.0"
    build:
      context: ./_mirror
      dockerfile: Dockerfile
    stop_signal: SIGINT
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./_mirror:/mirror
      - ./_nginx/acl:/mirror/nginx_acl
      - mirror-venv-data:/mirror/.venv
    depends_on:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          memory: 32M
    networks:
      mirror_net:
        ipv4_address: 172.200.0.10
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  xray:
    image: "kum_xray:v26.3.27"
    build:
      context: ./_xray
    stop_signal: SIGINT
    restart: unless-stopped
#    ports:
#      - "1080:8118"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./_xray/confs:/usr/local/etc/xray
      - ./_xray/geodata:/usr/local/share/xray
      - ./_xray/logs:/var/log/xray
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          memory: 16M
    depends_on:
      - nginx
    networks:
      mirror_net:
        ipv4_address: 172.200.0.5
    extra_hosts:
      - "kerio-updates-mirror.local:172.200.0.20"
      - "bda-update.kerio.com:172.200.0.20"
      - "bdupdate.kerio.com:172.200.0.20"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  tor:
    image: "kum_tor:v0.4.9.11"
    build:
      context: ./_tor
    stop_signal: SIGINT
    restart: unless-stopped
#    ports:
#      - "9050:9050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./_tor/start.sh:/tor/start.sh
      - ./_tor/tor.config:/etc/tor/torrc
      - ./_tor/bridges:/tor/bridges
      - ./_tor/check_tor:/tor/check_tor
      - tor-data:/var/lib/tor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          memory: 16M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    depends_on:
      - nginx
      - xray
    networks:
      mirror_net:
        ipv4_address: 172.200.0.30
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  tor-data:
    driver: local
  mirror-venv-data:
    driver: local

networks:
  # 172.200.0.5  - xray
  # 172.200.0.10 - mirror
  # 172.200.0.20 - nginx
  # 172.200.0.30 - tor
  mirror_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/24
          gateway: 172.200.0.1