# tinyproxy.conf file example:
# https://raw.githubusercontent.com/tinyproxy/tinyproxy/refs/heads/master/etc/tinyproxy.conf.in

# User/Group: This allows you to set the user and group that will be
# used for tinyproxy after the initial binding to the port has been done
# as the root user. Either the user or group name or the UID or GID
# number may be used.
User nobody
Group nobody

# Port: Specify the port which tinyproxy will listen on.  Please note
# that should you choose to run on a port lower than 1024 you will need
# to start tinyproxy using root.
Port 8118

# Timeout: The maximum number of seconds of inactivity a connection is
# allowed to have before it is closed by tinyproxy.
Timeout 120

# Set the logging level. Allowed settings are:
#	Critical	(least verbose)
#	Error
#	Warning
#	Notice
#	Connect		(to log connections without Info's noise)
#	Info		(most verbose)
#
# The LogLevel logs from the set level and above. For example, if the
# LogLevel was set to Warning, then all log messages from Warning to
# Critical would be output, but Notice and below would be suppressed.
LogLevel Connect

# Direct access for all
# upstream none "*"

# Direct access for specific domains
upstream none "kerio-updates-mirror.local"
upstream none "bda-update.kerio.com"
upstream none "bdupdate.kerio.com"

# All other traffic goes through upstream proxy
#
# Examples:
# upstream http proxy_ip:proxy_port
# upstream http username:password@proxy_ip:proxy_port
# upstream socks5 proxy_ip:proxy_port
# upstream socks5 username:password@proxy_ip:proxy_port
#
# Default upstream proxy - Local TOR
upstream socks5 172.200.0.30:9050

# MaxClients: This is the absolute highest number of threads which will
# be created. In other words, only MaxClients number of clients can be
# connected at the same time.
MaxClients 50

# Allow: Customization of authorization controls. If there are any
# access control keywords then the default action is to DENY. Otherwise,
# the default action is ALLOW.
#
# The order of the controls are important. All incoming connections are
# tested against the controls based on order.
Allow 172.200.0.0/24


# DisableViaHeader: When this is set to yes, Tinyproxy does NOT add
# the Via header to the requests. This virtually puts Tinyproxy into
# stealth mode. Note that RFC 2616 requires proxies to set the Via
# header, so by enabling this option, you break compliance.
# Don't disable the Via header unless you know what you are doing...
#
DisableViaHeader Yes
